name: deploy to S3

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: knockdog-landing-page-deploy-bucket
  CODE_DEPLOY_APPLICATION_NAME: knockdog-landingpage
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: landing-page-prod

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build next app
        run: pnpm run build

      - name: Make deploy script executable
        run: chmod +x scripts/deploy.sh

      - name: Prepare deploy package
        run: |
          mkdir -p deploy
          cp -r .next public package.json pnpm-lock.yaml .env appspec.yml ecosystem.config.js scripts deploy/
          cd deploy
          zip -qq -r ../landingpage.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./landingpage.zip s3://$S3_BUCKET_NAME/landingpage.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=landingpage.zip
