# 워크플로우 이름
name: deploy to S3

on:
  push:
    # main 브랜치에 push 시, 워크플로우 실행
    branches:
      - main

    # 워크플로우 실행 제외 목록
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - '**/*.md'
      - '**/LICENSE*'

# 워크플로우에서 사용되는 환경 변수
env:
  AWS_REGION: ap-northeast-2 # AWS 리전
  AWS_S3_BUCKET_NAME: knockdog-landing-page # S3 버킷 이름

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_INSTALLATION_ID: ${{ secrets.GH_INSTALLATION_ID }}
      GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
      GH_OWNER: ${{ vars.GH_OWNER }}
      GH_REPO: ${{ vars.GH_REPO }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1. 레포지토리 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. pnpm 전역 설치
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      # 3. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # 4. pnpm 의존성 설치
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. Next.js 빌드
      - name: Build next app
        run: pnpm run build

      # 6. AWS 접근 권한 부여
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      # 7. 빌드된 파일 S3 버킷에 정적 배포
      - name: Deploy to S3
        run: aws s3 sync --region ${{ env.AWS_REGION }} ./out s3://${{ env.AWS_S3_BUCKET_NAME }}/ --delete

      # 8. CloudFront 캐시 무효화
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
